export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  DASHBOARD: "/dashboard",
  TRANSACTIONS: "/transactions",
  ANALYTICS: "/analytics",
  BUDGETS: "/budgets",
  GOALS: "/goals",
  RECURRING: "/recurring",
  AI: "/ai-assistant",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  SETTINGS: "/settings",
};
